// Approximate nutrition per 100g. You can expand this table anytime.
module.exports = {
  data: {
    apple:     { kcal: 52,  protein: 0.3, carbs: 14, fat: 0.2 },
    banana:    { kcal: 89,  protein: 1.1, carbs: 23, fat: 0.3 },
    orange:    { kcal: 47,  protein: 0.9, carbs: 12, fat: 0.1 },
    strawberry:{ kcal: 33,  protein: 0.7, carbs: 8,  fat: 0.3 },
    tomato:    { kcal: 18,  protein: 0.9, carbs: 3.9,fat: 0.2 },
    cucumber:  { kcal: 16,  protein: 0.7, carbs: 3.6,fat: 0.1 },
    pizza:     { kcal: 266, protein: 11,  carbs: 33, fat: 10 }, // per 100g of generic pizza
    hamburger: { kcal: 295, protein: 17,  carbs: 24, fat: 15 },
    fries:     { kcal: 312, protein: 3.4, carbs: 41, fat: 15 },
    pasta:     { kcal: 131, protein: 5,   carbs: 25, fat: 1.1 },
    rice:      { kcal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
    bread:     { kcal: 265, protein: 9,   carbs: 49, fat: 3.2 },
    egg:       { kcal: 155, protein: 13,  carbs: 1.1,fat: 11 },
    chicken:   { kcal: 165, protein: 31,  carbs: 0,  fat: 3.6 }, // skinless breast
    beef:      { kcal: 250, protein: 26,  carbs: 0,  fat: 15 },
    fish:      { kcal: 206, protein: 22,  carbs: 0,  fat: 12 },
    cheese:    { kcal: 402, protein: 25,  carbs: 1.3,fat: 33 },
    yogurt:    { kcal: 59,  protein: 10,  carbs: 3.6,fat: 0.4 },
    milk:      { kcal: 60,  protein: 3.2, carbs: 5,  fat: 3.3 },
    salad:     { kcal: 20,  protein: 1,   carbs: 3.7,fat: 0.2 }
  },
  // Map model labels/aliases to our keys above
  alias: {
    'granny_smith': 'apple',
    'apple_pie': 'apple',
    'banana': 'banana',
    'orange': 'orange',
    'strawberry_shortcake': 'strawberry',
    'strawberry': 'strawberry',
    'tomato_soup': 'tomato',
    'tomato': 'tomato',
    'cucumber': 'cucumber',
    'pizza': 'pizza',
    'hamburger': 'hamburger',
    'french_fries': 'fries',
    'spaghetti_carbonara': 'pasta',
    'spaghetti_bolognese': 'pasta',
    'pasta': 'pasta',
    'fried_rice': 'rice',
    'rice': 'rice',
    'bread': 'bread',
    'omelette': 'egg',
    'scrambled_eggs': 'egg',
    'egg': 'egg',
    'chicken_curry': 'chicken',
    'chicken_wings': 'chicken',
    'chicken': 'chicken',
    'steak': 'beef',
    'beef_carpaccio': 'beef',
    'beef': 'beef',
    'grilled_salmon': 'fish',
    'fish_and_chips': 'fish',
    'fish': 'fish',
    'cheesecake': 'cheese',
    'cheddar_cheese': 'cheese',
    'cheese': 'cheese',
    'yogurt': 'yogurt',
    'milkshake': 'milk',
    'milk': 'milk',
    'caesar_salad': 'salad',
    'green_salad': 'salad',
    'salad': 'salad'
  }
};
